---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/consumer/accessories":
    get:
      summary: Get a list of accessories
      tags:
      - Accessory
      responses:
        '200':
          description: Accessories found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  brand:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - brand
                - price
                - quantity
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  brand:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - brand
                - price
                - quantity
        '422':
          description: invalid request
    post:
      summary: Create a new Accessory
      tags:
      - Accessory
      parameters: []
      responses:
        '201':
          description: accessory updated successfully
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                brand:
                  type: string
                price:
                  type: float
                quantity:
                  type: integer
              required:
              - name
              - brand
              - price
              - quantity
  "/consumer/accessories/{id}":
    get:
      summary: Retrieves a accessory
      tags:
      - Accessory
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: accessory found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  brand:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - brand
                - price
                - quantity
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  brand:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - brand
                - price
                - quantity
        '404':
          description: Accessory not found
    patch:
      summary: Update a Accessory
      tags:
      - Accessory
      parameters: []
      responses:
        '201':
          description: accessory updated successfully
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                brand:
                  type: string
                price:
                  type: float
                quantity:
                  type: integer
              required:
              - id
              - name
              - brand
              - price
              - quantity
    delete:
      summary: Delete a accessory
      tags:
      - Accessory
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: accessory deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
        '404':
          description: Accessory not found
  "/consumer/essences":
    get:
      summary: Get a list of essences
      tags:
      - Essence
      responses:
        '200':
          description: Essences found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  brand:
                    type: string
                  flavor:
                    type: string
                  size:
                    type: float
                  strength:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - brand
                - price
                - quantity
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  brand:
                    type: string
                  flavor:
                    type: string
                  size:
                    type: float
                  strength:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - brand
                - price
                - quantity
        '422':
          description: invalid request
    post:
      summary: Create a new Essence
      tags:
      - Essence
      parameters: []
      responses:
        '201':
          description: essence created successfully
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                brand:
                  type: string
                flavor:
                  type: string
                size:
                  type: float
                strength:
                  type: string
                price:
                  type: float
                quantity:
                  type: integer
              required:
              - name
              - brand
              - price
              - quantity
  "/consumer/essences/{id}":
    get:
      summary: Retrieves a essence
      tags:
      - Essence
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: essence found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  brand:
                    type: string
                  flavor:
                    type: string
                  size:
                    type: float
                  strength:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - brand
                - price
                - quantity
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  brand:
                    type: string
                  flavor:
                    type: string
                  size:
                    type: float
                  strength:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - brand
                - price
                - quantity
        '404':
          description: Essence not found
    patch:
      summary: Update a Essence
      tags:
      - Essence
      parameters: []
      responses:
        '201':
          description: essence updated successfully
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                brand:
                  type: string
                flavor:
                  type: string
                size:
                  type: float
                strength:
                  type: string
                price:
                  type: float
                quantity:
                  type: integer
              required:
              - id
              - name
              - brand
              - price
              - quantity
    delete:
      summary: Delete a essence
      tags:
      - Essence
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: essence deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
        '404':
          description: Essence not found
  "/":
    get:
      summary: Get a list of products
      tags:
      - Products
      responses:
        '200':
          description: Products found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  warrrancy:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - warrrancy
                - price
                - quantity
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  warrrancy:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - warrrancy
                - price
                - quantity
        '422':
          description: invalid request
  "/consumer/users":
    get:
      summary: Get a list of users
      tags:
      - Users
      responses:
        '200':
          description: Users found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                required:
                - id
                - username
                - email
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                required:
                - id
                - username
                - email
        '422':
          description: invalid request
  "/consumer/vapes":
    get:
      summary: Get a list of vapes
      tags:
      - Vape
      responses:
        '200':
          description: Vapes found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  warrrancy:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - warrrancy
                - price
                - quantity
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  warrrancy:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - warrrancy
                - price
                - quantity
        '422':
          description: invalid request
    post:
      summary: Create a new Vape
      tags:
      - Vape
      parameters: []
      responses:
        '201':
          description: vape updated successfully
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                brand:
                  type: string
                warrancy:
                  type: string
                price:
                  type: string
                quantity:
                  type: string
              required:
              - name
              - brand
              - warrancy
              - price
              - quantity
  "/consumer/vapes/{id}":
    get:
      summary: Retrieves a vape
      tags:
      - Vape
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: vape found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  warrrancy:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - warrrancy
                - price
                - quantity
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  warrrancy:
                    type: string
                  price:
                    type: float
                  quantity:
                    type: integer
                required:
                - id
                - name
                - warrrancy
                - price
                - quantity
        '404':
          description: Vape not found
    patch:
      summary: Update a Vape
      tags:
      - Vape
      parameters: []
      responses:
        '201':
          description: vape updated successfully
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                brand:
                  type: string
                warrancy:
                  type: integer
                price:
                  type: float
                quantity:
                  type: integer
              required:
              - id
              - name
              - brand
              - warrancy
              - price
              - quantity
    delete:
      summary: Delete a vape
      tags:
      - Vape
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: vape deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
        '404':
          description: Vape not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
- url: https://{herokuDev}
  variables:
    herokuDev:
      default: rails-store-joaobitencourt.herokuapp.com
- url: https://{herokuProd}
  variables:
    herokuProd:
      default: joaobitencourt.herokuapp.com/
